#!/bin/sh

set -e

# This is the default location.  If you have changed it in the config,
# you will simply need to clean up sessions yourself, because we can't
# read the config with tools which are guaranteed to be installed and
# available.
rootOfSessions='/var/lib/chleb-bible-search/sessions/'

isSharedFileSystem() {
	fsType="$1"

	sharedFileSystemList="cifs nfs dummy"

	for sharedFsType in $sharedFileSystemList; do
		if [ "$fsType" = "$sharedFsType" ]; then
			return 0
		fi
	done

	return 1
}

getFsType() {
	dirName="$1"

	if [ -d "$dirName" ]; then
		fsType=$(stat -f -c %T "$dirName")
		echo "$fsType"
	else
		>&2 echo "WARNING: '$dirName' not found"
		echo 'dummy' # we always have to succeed to avoid broken packages
	fi

	return 0
}

maybeSessionCleanup() {
	dirName="$1"

	fsType=$(getFsType "$dirName")
	if isSharedFileSystem "$fsType"; then
		if [ "$fsType" != 'dummy' ]; then
			>&2 echo "INFO: Not purging sessions on a shared mount-point - '$dirName' of type $fsType"
		fi
		return 0
	fi

	sessionCleanup "$dirName"
	return 0
}

sessionCleanup() {
	dirName="$1"

	find "$dirName" -name "*.session" -type f -delete

	for i in $(seq 4 -1 1); do
		find "$dirName" -mindepth $i -maxdepth $i -type d -delete
	done

	return 0
}

case "$1" in
	purge)
		echo "DEBUG: package $1"
		maybeSessionCleanup "$rootOfSessions"
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		echo "DEBUG: package $1"
		;;
esac

#DEBHELPER#

exit 0
