#!/bin/sh

set -e

[ -z "$SERVER_USER" ] && SERVER_USER=chleb
[ -z "$SERVER_NAME" ] && SERVER_NAME="Chleb Bible Search"

if ! getent passwd | grep -q "^$SERVER_USER:"; then
	echo -n "Adding system user $SERVER_USER.."
	adduser --quiet \
		--system \
		--no-create-home \
		--home /nonexistent \
		--disabled-password \
		$SERVER_USER 2>/dev/null || true
	echo "..done"
fi

usermod -c "$SERVER_NAME" $SERVER_USER
chown $SERVER_USER /var/log/chleb-bible-search /var/cache/chleb-bible-search /var/run/chleb-bible-search
chmod 0755 /var/run/chleb-bible-search

if [ -f /var/log/chleb-bible-search/default.log ]; then
	chown $SERVER_USER /var/log/chleb-bible-search/default.log
fi

echo 'clearing bible translation cache'
rm -f /var/cache/chleb-bible-search/*.bin

echo 'cleaing old session files'
/usr/share/chleb-bible-search/session-clean.sh
echo 'installing symbolic link run script'
cp -lf /usr/share/chleb-bible-search/run.sh /usr/bin/chleb-bible-search/run.sh

invoke-rc.d chleb-bible-search restart || :

#DEBHELPER#

exit 0
