#!/bin/sh

[ -z "$SERVER_USER" ] && SERVER_USER=chleb
[ -z "$SERVER_NAME" ] && SERVER_NAME="Chleb Bible Search"

if ! getent passwd | grep -q "^$SERVER_USER:"; then
	echo -n "Adding system user $SERVER_USER.."
	adduser --quiet \
		--system \
		--no-create-home \
		--disabled-password \
		$SERVER_USER 2>/dev/null || true
	echo "..done"
fi

usermod -c "$SERVER_NAME" $SERVER_USER
chown $SERVER_USER /var/log/chleb-bible-search/default.log

/usr/bin/systemctl start chleb-bible-search
/usr/bin/systemctl enable chleb-bible-search

exit 0
