#!/bin/sh

set -e

invoke-rc.d chleb-bible-search stop || :

echo 'removing symlink run script'
rm -vf '/usr/bin/chleb-bible-search/run.sh'

echo 'clearing bible translation cache'
rm -f /var/cache/chleb-bible-search/*.bin

#DEBHELPER#

exit 0
