EOWNERDEAD	130	"Owner died"
ENOTCONN	107	"Transport endpoint is not connected"
EBADR	53	"Invalid request descriptor"
EOVERFLOW	75	"Value too large for defined data type"
ENOTNAM	118	"Not a XENIX named type file"
EPFNOSUPPORT	96	"Protocol family not supported"
ENXIO	6	"No such device or address"
EDEADLOCK	35	"Resource deadlock avoided"
EPROTO	71	"Protocol error"
ENOANO	55	"No anode"
EDOTDOT	73	"RFS specific error"
ENOBUFS	105	"No buffer space available"
EILSEQ	84	"Invalid or incomplete multibyte or wide character"
EINTR	4	"Interrupted system call"
ELIBEXEC	83	"Cannot exec a shared library directly"
ECONNRESET	104	"Connection reset by peer"
EIO	5	"Input/output error"
ECONNREFUSED	111	"Connection refused"
ENOTRECOVERABLE	131	"State not recoverable"
EXFULL	54	"Exchange full"
ECOMM	70	"Communication error on send"
EISNAM	120	"Is a named type file"
EL3RST	47	"Level 3 reset"
ELIBBAD	80	"Accessing a corrupted shared library"
ERFKILL	132	"Operation not possible due to RF-kill"
EISDIR	21	"Is a directory"
EWOULDBLOCK	11	"Resource temporarily unavailable"
EHOSTUNREACH	113	"No route to host"
ESHUTDOWN	108	"Cannot send after transport endpoint shutdown"
ENOTUNIQ	76	"Name not unique on network"
ELNRNG	48	"Link number out of range"
EPROTONOSUPPORT	93	"Protocol not supported"
ENETDOWN	100	"Network is down"
EFAULT	14	"Bad address"
ENOTDIR	20	"Not a directory"
EINVAL	22	"Invalid argument"
EEXIST	17	"File exists"
EL2NSYNC	45	"Level 2 not synchronized"
ENOTSUP	95	"Operation not supported"
EADDRNOTAVAIL	99	"Cannot assign requested address"
EPERM	1	"Operation not permitted"
ELIBMAX	82	"Attempting to link in too many shared libraries"
EMLINK	31	"Too many links"
EMEDIUMTYPE	124	"Wrong medium type"
ETIME	62	"Timer expired"
EBADE	52	"Invalid exchange"
ENOTEMPTY	39	"Directory not empty"
EMFILE	24	"Too many open files"
ENOTTY	25	"Inappropriate ioctl for device"
EMULTIHOP	72	"Multihop attempted"
ETXTBSY	26	"Text file busy"
ESRMNT	69	"Srmount error"
ENOPROTOOPT	92	"Protocol not available"
EREMCHG	78	"Remote address changed"
EHOSTDOWN	112	"Host is down"
EPIPE	32	"Broken pipe"
EUSERS	87	"Too many users"
ERANGE	34	"Numerical result out of range"
EKEYEXPIRED	127	"Key has expired"
ESTRPIPE	86	"Streams pipe error"
ENOSTR	60	"Device not a stream"
ENETRESET	102	"Network dropped connection on reset"
EADV	68	"Advertise error"
EBADRQC	56	"Invalid request code"
ESOCKTNOSUPPORT	94	"Socket type not supported"
EKEYREJECTED	129	"Key was rejected by service"
ENOMEM	12	"Cannot allocate memory"
ENODATA	61	"No data available"
ENOEXEC	8	"Exec format error"
EKEYREVOKED	128	"Key has been revoked"
EUCLEAN	117	"Structure needs cleaning"
ENONET	64	"Machine is not on the network"
EBFONT	59	"Bad font file format"
EISCONN	106	"Transport endpoint is already connected"
ENOMEDIUM	123	"No medium found"
ECONNABORTED	103	"Software caused connection abort"
ENOCSI	50	"No CSI structure available"
EHWPOISON	133	"Memory page has hardware error"
EREMOTE	66	"Object is remote"
EINPROGRESS	115	"Operation now in progress"
ETOOMANYREFS	109	"Too many references: cannot splice"
EBADFD	77	"File descriptor in bad state"
EBADF	9	"Bad file descriptor"
EL3HLT	46	"Level 3 halted"
E2BIG	7	"Argument list too long"
ENOLINK	67	"Link has been severed"
EALREADY	114	"Operation already in progress"
EREMOTEIO	121	"Remote I/O error"
ERESTART	85	"Interrupted system call should be restarted"
EMSGSIZE	90	"Message too long"
EXDEV	18	"Invalid cross-device link"
EIDRM	43	"Identifier removed"
ENAVAIL	119	"No XENIX semaphores available"
ESPIPE	29	"Illegal seek"
ENAMETOOLONG	36	"File name too long"
ENOSYS	38	"Function not implemented"
EOPNOTSUPP	95	"Operation not supported"
ENOSR	63	"Out of streams resources"
ENOENT	2	"No such file or directory"
ENOPKG	65	"Package not installed"
EACCES	13	"Permission denied"
ENETUNREACH	101	"Network is unreachable"
ECHRNG	44	"Channel number out of range"
EPROTOTYPE	91	"Protocol wrong type for socket"
ETIMEDOUT	110	"Connection timed out"
EDESTADDRREQ	89	"Destination address required"
EDOM	33	"Numerical argument out of domain"
ESTALE	116	"Stale file handle"
EL2HLT	51	"Level 2 halted"
ESRCH	3	"No such process"
ENOKEY	126	"Required key not available"
EDEADLK	35	"Resource deadlock avoided"
ENFILE	23	"Too many open files in system"
ELOOP	40	"Too many levels of symbolic links"
ECHILD	10	"No child processes"
EBADMSG	74	"Bad message"
EROFS	30	"Read-only file system"
EUNATCH	49	"Protocol driver not attached"
ELIBACC	79	"Can not access a needed shared library"
ENOSPC	28	"No space left on device"
EAGAIN	11	"Resource temporarily unavailable"
ENOTBLK	15	"Block device required"
EBADSLT	57	"Invalid slot"
ECANCELED	125	"Operation canceled"
EAFNOSUPPORT	97	"Address family not supported by protocol"
EDQUOT	122	"Disk quota exceeded"
EADDRINUSE	98	"Address already in use"
EFBIG	27	"File too large"
ENOMSG	42	"No message of desired type"
ELIBSCN	81	".lib section in a.out corrupted"
ENODEV	19	"No such device"
ENOLCK	37	"No locks available"
EBUSY	16	"Device or resource busy"
ENOTSOCK	88	"Socket operation on non-socket"
