package Chleb::Utils::OSError::Mapper;
use strict;
use warnings;

use HTTP::Status qw(:constants);
use Readonly;

Readonly my %MAPPINGS => (
	EOWNERDEAD	=> HTTP_INTERNAL_SERVER_ERROR,			# Owner died
	ENOTCONN	=> HTTP_INTERNAL_SERVER_ERROR,			# Transport endpoint is not connected
	EBADR		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid request descriptor
	EOVERFLOW	=> HTTP_INTERNAL_SERVER_ERROR,			# Value too large for defined data type
	ENOTNAM		=> HTTP_INTERNAL_SERVER_ERROR,			# Not a XENIX named type file
	EPFNOSUPPORT	=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol family not supported
	ENXIO		=> HTTP_INTERNAL_SERVER_ERROR,			# No such device or address
	EDEADLOCK	=> HTTP_INTERNAL_SERVER_ERROR,			# Resource deadlock avoided
	EPROTO		=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol error
	ENOANO		=> HTTP_INTERNAL_SERVER_ERROR,			# No anode
	EDOTDOT		=> HTTP_INTERNAL_SERVER_ERROR,			# RFS specific error
	ENOBUFS		=> HTTP_INTERNAL_SERVER_ERROR,			# No buffer space available
	EILSEQ		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid or incomplete multibyte or wide character
	EINTR		=> HTTP_INTERNAL_SERVER_ERROR,			# Interrupted system call
	ELIBEXEC	=> HTTP_INTERNAL_SERVER_ERROR,			# Cannot exec a shared library directly
	ECONNRESET	=> HTTP_INTERNAL_SERVER_ERROR,			# Connection reset by peer
	EIO		=> HTTP_INTERNAL_SERVER_ERROR,			# Input/output error
	ECONNREFUSED	=> HTTP_INTERNAL_SERVER_ERROR,			# Connection refused
	ENOTRECOVERABLE	=> HTTP_INTERNAL_SERVER_ERROR,			# State not recoverable
	EXFULL		=> HTTP_INTERNAL_SERVER_ERROR,			# Exchange full
	ECOMM		=> HTTP_INTERNAL_SERVER_ERROR,			# Communication error on send
	EISNAM		=> HTTP_INTERNAL_SERVER_ERROR,			# Is a named type file
	EL3RST		=> HTTP_INTERNAL_SERVER_ERROR,			# Level 3 reset
	ELIBBAD		=> HTTP_INTERNAL_SERVER_ERROR,			# Accessing a corrupted shared library
	ERFKILL		=> HTTP_INTERNAL_SERVER_ERROR,			# Operation not possible due to RF-kill
	EISDIR		=> HTTP_INTERNAL_SERVER_ERROR,			# Is a directory
	EWOULDBLOCK	=> HTTP_INTERNAL_SERVER_ERROR,			# Resource temporarily unavailable
	EHOSTUNREACH	=> HTTP_INTERNAL_SERVER_ERROR,			# No route to host
	ESHUTDOWN	=> HTTP_INTERNAL_SERVER_ERROR,			# Cannot send after transport endpoint shutdown
	ENOTUNIQ	=> HTTP_INTERNAL_SERVER_ERROR,			# Name not unique on network
	ELNRNG		=> HTTP_INTERNAL_SERVER_ERROR,			# Link number out of range
	EPROTONOSUPPORT	=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol not supported
	ENETDOWN	=> HTTP_INTERNAL_SERVER_ERROR,			# Network is down
	EFAULT		=> HTTP_INTERNAL_SERVER_ERROR,			# Bad address
	ENOTDIR		=> HTTP_INTERNAL_SERVER_ERROR,			# Not a directory
	EINVAL		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid argument
	EEXIST		=> HTTP_INTERNAL_SERVER_ERROR,			# File exists
	EL2NSYNC	=> HTTP_INTERNAL_SERVER_ERROR,			# Level 2 not synchronized
	ENOTSUP		=> HTTP_INTERNAL_SERVER_ERROR,			# Operation not supported
	EADDRNOTAVAIL	=> HTTP_INTERNAL_SERVER_ERROR,			# Cannot assign requested address
	EPERM		=> HTTP_INTERNAL_SERVER_ERROR,			# Operation not permitted
	ELIBMAX		=> HTTP_INTERNAL_SERVER_ERROR,			# Attempting to link in too many shared libraries
	EMLINK		=> HTTP_INTERNAL_SERVER_ERROR,			# Too many links
	EMEDIUMTYPE	=> HTTP_INTERNAL_SERVER_ERROR,			# Wrong medium type
	ETIME		=> HTTP_INTERNAL_SERVER_ERROR,			# Timer expired
	EBADE		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid exchange
	ENOTEMPTY	=> HTTP_INTERNAL_SERVER_ERROR,			# Directory not empty
	EMFILE		=> HTTP_INTERNAL_SERVER_ERROR,			# Too many open files
	ENOTTY		=> HTTP_INTERNAL_SERVER_ERROR,			# Inappropriate ioctl for device
	EMULTIHOP	=> HTTP_INTERNAL_SERVER_ERROR,			# Multihop attempted
	ETXTBSY		=> HTTP_INTERNAL_SERVER_ERROR,			# Text file busy
	ESRMNT		=> HTTP_INTERNAL_SERVER_ERROR,			# Srmount error
	ENOPROTOOPT	=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol not available
	EREMCHG		=> HTTP_INTERNAL_SERVER_ERROR,			# Remote address changed
	EHOSTDOWN	=> HTTP_INTERNAL_SERVER_ERROR,			# Host is down
	EPIPE		=> HTTP_INTERNAL_SERVER_ERROR,			# Broken pipe
	EUSERS		=> HTTP_INTERNAL_SERVER_ERROR,			# Too many users
	ERANGE		=> HTTP_INTERNAL_SERVER_ERROR,			# Numerical result out of range
	EKEYEXPIRED	=> HTTP_INTERNAL_SERVER_ERROR,			# Key has expired
	ESTRPIPE	=> HTTP_INTERNAL_SERVER_ERROR,			# Streams pipe error
	ENOSTR		=> HTTP_INTERNAL_SERVER_ERROR,			# Device not a stream
	ENETRESET	=> HTTP_INTERNAL_SERVER_ERROR,			# Network dropped connection on reset
	EADV		=> HTTP_INTERNAL_SERVER_ERROR,			# Advertise error
	EBADRQC		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid request code
	ESOCKTNOSUPPORT	=> HTTP_INTERNAL_SERVER_ERROR,			# Socket type not supported
	EKEYREJECTED	=> HTTP_INTERNAL_SERVER_ERROR,			# Key was rejected by service
	ENOMEM		=> HTTP_INTERNAL_SERVER_ERROR,			# Cannot allocate memory
	ENODATA		=> HTTP_INTERNAL_SERVER_ERROR,			# No data available
	ENOEXEC		=> HTTP_INTERNAL_SERVER_ERROR,			# Exec format error
	EKEYREVOKED	=> HTTP_INTERNAL_SERVER_ERROR,			# Key has been revoked
	EUCLEAN		=> HTTP_INTERNAL_SERVER_ERROR,			# Structure needs cleaning
	ENONET		=> HTTP_INTERNAL_SERVER_ERROR,			# Machine is not on the network
	EBFONT		=> HTTP_INTERNAL_SERVER_ERROR,			# Bad font file format
	EISCONN		=> HTTP_INTERNAL_SERVER_ERROR,			# Transport endpoint is already connected
	ENOMEDIUM	=> HTTP_INTERNAL_SERVER_ERROR,			# No medium found
	ECONNABORTED	=> HTTP_INTERNAL_SERVER_ERROR,			# Software caused connection abort
	ENOCSI		=> HTTP_INTERNAL_SERVER_ERROR,			# No CSI structure available
	EHWPOISON	=> HTTP_INTERNAL_SERVER_ERROR,			# Memory page has hardware error
	EREMOTE		=> HTTP_INTERNAL_SERVER_ERROR,			# Object is remote
	EINPROGRESS	=> HTTP_INTERNAL_SERVER_ERROR,			# Operation now in progress
	ETOOMANYREFS	=> HTTP_INTERNAL_SERVER_ERROR,			# Too many references: cannot splice
	EBADFD		=> HTTP_INTERNAL_SERVER_ERROR,			# File descriptor in bad state
	EBADF		=> HTTP_INTERNAL_SERVER_ERROR,			# Bad file descriptor
	EL3HLT		=> HTTP_INTERNAL_SERVER_ERROR,			# Level 3 halted
	E2BIG		=> HTTP_INTERNAL_SERVER_ERROR,			# Argument list too long
	ENOLINK		=> HTTP_INTERNAL_SERVER_ERROR,			# Link has been severed
	EALREADY	=> HTTP_INTERNAL_SERVER_ERROR,			# Operation already in progress
	EREMOTEIO	=> HTTP_INTERNAL_SERVER_ERROR,			# Remote I/O error
	ERESTART	=> HTTP_INTERNAL_SERVER_ERROR,			# Interrupted system call should be restarted
	EMSGSIZE	=> HTTP_INTERNAL_SERVER_ERROR,			# Message too long
	EXDEV		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid cross-device link
	EIDRM		=> HTTP_INTERNAL_SERVER_ERROR,			# Identifier removed
	ENAVAIL		=> HTTP_INTERNAL_SERVER_ERROR,			# No XENIX semaphores available
	ESPIPE		=> HTTP_INTERNAL_SERVER_ERROR,			# Illegal seek
	ENAMETOOLONG	=> HTTP_INTERNAL_SERVER_ERROR,			# File name too long
	ENOSYS		=> HTTP_INTERNAL_SERVER_ERROR,			# Function not implemented
	EOPNOTSUPP	=> HTTP_INTERNAL_SERVER_ERROR,			# Operation not supported
	ENOSR		=> HTTP_INTERNAL_SERVER_ERROR,			# Out of streams resources
	ENOENT		=> HTTP_INTERNAL_SERVER_ERROR,			# No such file or directory
	ENOPKG		=> HTTP_INTERNAL_SERVER_ERROR,			# Package not installed
	EACCES		=> HTTP_INTERNAL_SERVER_ERROR,			# Permission denied
	ENETUNREACH	=> HTTP_INTERNAL_SERVER_ERROR,			# Network is unreachable
	ECHRNG		=> HTTP_INTERNAL_SERVER_ERROR,			# Channel number out of range
	EPROTOTYPE	=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol wrong type for socket
	ETIMEDOUT	=> HTTP_INTERNAL_SERVER_ERROR,			# Connection timed out
	EDESTADDRREQ	=> HTTP_INTERNAL_SERVER_ERROR,			# Destination address required
	EDOM		=> HTTP_INTERNAL_SERVER_ERROR,			# Numerical argument out of domain
	ESTALE		=> HTTP_INTERNAL_SERVER_ERROR,			# Stale file handle
	EL2HLT		=> HTTP_INTERNAL_SERVER_ERROR,			# Level 2 halted
	ESRCH		=> HTTP_INTERNAL_SERVER_ERROR,			# No such process
	ENOKEY		=> HTTP_INTERNAL_SERVER_ERROR,			# Required key not available
	EDEADLK		=> HTTP_INTERNAL_SERVER_ERROR,			# Resource deadlock avoided
	ENFILE		=> HTTP_INTERNAL_SERVER_ERROR,			# Too many open files in system
	ELOOP		=> HTTP_INTERNAL_SERVER_ERROR,			# Too many levels of symbolic links
	ECHILD		=> HTTP_INTERNAL_SERVER_ERROR,			# No child processes
	EBADMSG		=> HTTP_INTERNAL_SERVER_ERROR,			# Bad message
	EROFS		=> HTTP_INTERNAL_SERVER_ERROR,			# Read-only file system
	EUNATCH		=> HTTP_INTERNAL_SERVER_ERROR,			# Protocol driver not attached
	ELIBACC		=> HTTP_INTERNAL_SERVER_ERROR,			# Can not access a needed shared library
	ENOSPC		=> HTTP_INTERNAL_SERVER_ERROR,			# No space left on device
	EAGAIN		=> HTTP_INTERNAL_SERVER_ERROR,			# Resource temporarily unavailable
	ENOTBLK		=> HTTP_INTERNAL_SERVER_ERROR,			# Block device required
	EBADSLT		=> HTTP_INTERNAL_SERVER_ERROR,			# Invalid slot
	ECANCELED	=> HTTP_INTERNAL_SERVER_ERROR,			# Operation canceled
	EAFNOSUPPORT	=> HTTP_INTERNAL_SERVER_ERROR,			# Address family not supported by protocol
	EDQUOT		=> HTTP_INTERNAL_SERVER_ERROR,			# Disk quota exceeded
	EADDRINUSE	=> HTTP_INTERNAL_SERVER_ERROR,			# Address already in use
	EFBIG		=> HTTP_INTERNAL_SERVER_ERROR,			# File too large
	ENOMSG		=> HTTP_INTERNAL_SERVER_ERROR,			# No message of desired type
	ELIBSCN		=> HTTP_INTERNAL_SERVER_ERROR,			# .lib section in a.out corrupted
	ENODEV		=> HTTP_INTERNAL_SERVER_ERROR,			# No such device
	ENOLCK		=> HTTP_INTERNAL_SERVER_ERROR,			# No locks available
	EBUSY		=> HTTP_INTERNAL_SERVER_ERROR,			# Device or resource busy
	ENOTSOCK	=> HTTP_INTERNAL_SERVER_ERROR,			# Socket operation on non-socket
};

1;
