name: Perl CI

on:
  push:
    branches: [ "develop", "master", "f/202408-no-bins" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: recursion
      run: git submodule update --init --recursive

    - name: dlscripts
      run: git clone -q -b dlscripts-0.4.0 https://git.sr.ht/~m6kvm/dlscripts

    - name: dependencies
      run: sudo apt-get install -y `dlscripts/build-deps.sh debian/control`

    - name: ExtUtils::MakeMaker
      run: perl Makefile.PL

    - name: make
      run: make

    - name: local setup
      run: |
        ln -sf `pwd`/.github/etc/log4perl.conf etc/log4perl.conf
        mkdir -p build/var/log
        touch build/var/log/default.log

    - name: make test
      run: make test
