name: PR AI Notes
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write

jobs:
  ai-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Get PR diff (files & patch)
      - id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              per_page: 300,
            });
            const summaryInput = {
              title: pr.title,
              body: pr.body || "",
              files: files.map(f => ({
                filename: f.filename,
                status: f.status,
                additions: f.additions,
                deletions: f.deletions,
                patch: f.patch || ""
              }))
            };
            core.setOutput("input", JSON.stringify(summaryInput));

      # Call an AI PR summarizer action (choose ONE)
      - name: Generate AI PR summary & release notes
        uses: coderabbitai/ai-pr-reviewer@v1
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          language: "en"
          mode: "release-notes" # implementation-specific; see action docs

      # (Alternative) Roll your own call via curl – see DIY option below
